### PR TITLE
adds config option to indicate host validation should be disabled for cf ssh (-k flag)

### PR DESCRIPTION
**Pull request by ekcasey**
We need this change to run dats against microPCF

### CODE REVIEW

**Comment by robdimsdale** [comment]
@ekcasey @sclevine can you make sure you've both signed the CLA and made memberships public on github please

**Comment by robdimsdale** [comment]
Merged, thanks. We will bump this dependency in CATS now

**Comment by robdimsdale** [comment]
also @sclevine @ekcasey and @keaty FYI we've merged DATS into CATS

**Comment by sclevine** [comment]
Thanks @robdimsdale! We just noticed that today and will be adjusting our CI accordingly.

**Pull request merged**
